### ISSUE TITLE
web_accessible_resources and UUID leaking

### ISSUE THREAD

**Issue by atomGit** [aureliendavid/rsspreview#59] opened 2020-09-27 02:06 UTC
i was just doing some long overdue reading on how extensions (and in turn the browser) can be fingerprinted and i see that if an ext. uses "web_accessible_resources" (and JS is enabled), it's possible for a website to get the UUID of the ext.

in the RSSPreview manifest i'm seeing "web_accessible_resources" and i'd just like to get your take on whether it may be affected by this

[Bug 1405971](https://bugzilla.mozilla.org/show_bug.cgi?id=1405971)

**Comment by aureliendavid** [comment] 2024-05-10 15:32
Hello, 

Sorry for not responding earlier, I don't think I had a good take on this. 

I think the related firefox bug has been fixed in the meantime (even though it still appears open, I cannot reproduce the cited behavior). 

Either way I don't think this has an impact on rsspreview, or that I could do anything about it. 

So thanks for reporting and sorry for the unsatisfying answer. Feel free to reopen if there are more info on this.

**Closed by aureliendavid** 2024-05-10 15:32 UTC
