### ISSUE TITLE
Support for Fenix

### ISSUE THREAD

**Issue by afontenot** [aureliendavid/rsspreview#58] opened 2020-09-19 23:12 UTC
This might be a long-shot, but I wonder if you'd be able to add support for the current version of Fenix (i.e. the newest Firefox for Android rewrite). I've been using this extension on both Fennec and Desktop Firefox for a long time now and it's been a lifesaver, but I'm starting to worry about getting stuck on Fennec. 

Getting support for Fenix done would probably mean that it's available more quickly if Mozilla ever do actually expand the extensions program on mobile. Either way, there's actually a [fork](https://github.com/fork-maintainers/iceraven-browser) due to longstanding grievances with Mozilla's handling of the mobile browser. I tested this extension with that fork and it installs but seems non-functional.

**Comment by aureliendavid** [comment] 2020-09-22 15:36
Hi, thanks for the report. 

I wasn't aware of all this mess with the new firefox for android. It's a real shame that they would release a new browser without support for extensions. 

I tried to install it with this method https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/ on fenix main, nightly and the iceraven fork. 

On these three versions, the result is the same: the preview page works well (when visiting an rss url), the detection seem to work, however the popup page that shows the list of detected feeds on a page doesn't open, and the options page can't be opened either. 

The problem is that I found no documentation about what is supported, how it should be changed etc.. 

I'll try to find if `pageAction.setPopup() ; pageAction.show()` is supposed to work or what the alternative is. 

I'll keep this issue opened and report if I make progress. 

Any tip about porting to fenix and the like is welcome.

**Comment by afontenot** [comment] 2021-04-22 03:28
Tried on latest nightly. The situation appears to be slightly improved: 

When on a page with an RSS feed, `Menu > Add-ons > Feeds in page` will open the RSSPreview modal. A list of feeds is displayed, although the text is very small, so you have to zoom in. 

There's no indication that the feeds are links, but if you click on one, it will silently load the feed URL in a new tab in the background. If you then switch to that tab, RSSPreview appears to show a preview of the feed exactly as expected!

So although the result is still buggy, it's at least usable. I'd at least consider updating from Firefox 68, but unfortunately that would mean getting stuck with nightly until they allow more extensions to be installed. (The new Firefox for Android is also much slower on my phone than the old one. Not sure why.)

> The problem is that I found no documentation about what is supported, how it should be changed etc..

That's Mozilla for you. :-)

**Comment by Matth7878** [comment] 2023-08-31 08:39
Any progress about this issue? Mozilla plan to open add-ons for mobile. See their article [Prepare your Firefox desktop extension for the upcoming Android release](https://blog.mozilla.org/addons/2023/08/10/prepare-your-firefox-desktop-extension-for-the-upcoming-android-release/) published in August 10th 2023.
Hope it will allow to have a decent way to get RSS links on Android. 🤞

**Comment by aureliendavid** [comment] 2024-04-15 13:17
HI, 

Thanks for your interest. I am interesting in bringing it to android, but the last time I checked (a good while ago), it wasn't really possible to get small extensions working there. 

I haven't looked at it lately but if it's more open now I'll look at it again when I find the time.

I'll update here when I have news to share. 

Thanks for you patience!

**Comment by aureliendavid** [comment] 2024-05-03 13:25
support for extensions on firefox for android has indeed vastly improved (thanks @SamuelSwartzberg for the heads up)

I pushed a new version of the extension with some fixes for android

if you have a recent version of firefox for android (v121.0 and up) you should now be able to install RSSPreview directly from its AMO page at https://addons.mozilla.org/en-US/firefox/addon/rsspreview/ and it should work the same as on desktop

(it looks like there is no need to create a custom collection and all that stuff anymore)

@afontenot your original issue is almost 4 years old now so I don't know if you're still interested, but better late than never i guess :) 

thx all

**Comment by aureliendavid** [comment] 2024-05-10 15:19
I'm closing this. 

Feel free to open specific issues for android. 

thanks

**Closed by aureliendavid** 2024-05-10 15:19 UTC
